# Atençao: Não tem como rodar duas vezes o Job(apply seguidos), para rodar novamente este arquivo deve-se apagar o job, pois ele é uma tarefa finita e imutável.
apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
# Caso queira configurar o número de vezes a rodar para realizar multiplas tarefas adicione o campo:
  completions: 5 # O padrão é 1(Um pod por tarefa), neste caso teremos 5 pods, cada um com uma tarefa. SOMENTE UM é executado por VEZ
  completionMode: "Indexed" # Adiciona index ao nome do job(0, 1, ...), podemos visualizar isso com get jobs
  parallelism: 5 # O padrão é 1, neste caso teremos 5 pods rodando ao mesmo tempo realizando as tarefas.
  backoffLimit: 3 # O padrão é 6, este campo é o número de vezes que o job irá tentar rodar caso haja falha. Após atingir o limite, o job é considerado como falho.
  activeDeadlineSeconds: 100 # O padrão é infinito, este campo é o tempo máximo que o job pode ficar ativo. Após atingir o limite, o job é considerado como falho e os pods são parados mesmo se estiver em execução ainda.
  template:
    metadata:
      name: my-job-pod
    spec:
      containers:
      - name: my-container-busybox
        image: busybox
        command:
        - "bin/sh"
        - "-c"
        # gerando número aleatório entre 1 e 70
        - "for i in 1 2; do echo Lucky number $i = $((1 + ramdom % 70)); done"
      # O restartPolicy é ligado as specs do Pod e não do Job, por isso é necessário colocar dentro do template
      restartPolicy: Never

# kubectl describe job my-job	-> visualizar descrição do job
# kubectl logs my-job-879yh	-> visualizar log do job. Rode o get pods para poder pegar o nome do pod para jogar neste comando.
# kubectl describe pod my-job-879yh -> visualizar descrição do pod