apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
  spec:
    containers:
    
    - name: apache-container
      image: httpd
      # Recursos mínimos para rodar o container
      resources:
        requests:
          cpu: "500m" # 500 millicores de CPU(meia cpu)
          memory: "128Mi" # 128 megabytes de memória
        limits:
          cpu: "1000m" # 1000 millicores de CPU(1 CPU)
          memory: "256Mi" # 256 megabytes de memória

          # Use o comando kubectl describe pod para poder visualizar os recursos solicitados

    - name: redis-container
      image: redis
      resources:
        requests:
          cpu: "400m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"