apiVersion: v1
kind: PersistentVolume
metadata:
  name: disco-rede-app
spec:
  capacity:
    storage: 50Gi
  # Diferencial Crítico: Permite que múltiplos Pods leiam e escrevam ao mesmo tempo
  accessModes:
    - ReadWriteMany
  # Mantém os dados seguros caso o PVC seja acidentalmente deletado
  persistentVolumeReclaimPolicy: Retain
  
  # Usando Armazenamento de Rede (O padrão profissional)
  # Em nuvem AWS, seria o "csi" da Amazon EFS. Aqui usamos NFS nativo.
  nfs:
    server: 10.0.5.105 # O IP do seu storage de rede
    path: "/exports/dados-app"