apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
# Não podemos modificar o type do secret depois que ele é criado, pois ele é uma propriedade imutável
type: kubernetes.io/basic-auth
# Se usassemos o 'data', deveriamos usar o valor em base64. Podemos juntar data e stringData também
stringData:
  # Os nomes dos campos "username" e "password" são fixos para o tipo "kubernetes.io/basic-auth"
  username: admin
  password: Pass-123
  extra-key: value # Podemos colocar quantas chaves quisermos, não tem problema, o tipo "kubernetes.io/basic-auth" só tem a restrição de ter os campos "username" e "password", os outros campos são opcionais

# Para criar o secret use o comando:
# echo -n 'admin' | base64 -> trás a string em base64
# Para decodificar use o comando:
# echo -n 'YWRtaW4=' | base64 -d ou --decode -> decodifica a string em base64