apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  type: Opaque # Type padrão é Opaque, coloquei aqui sonte para questões didáticas
data: # Se caso quisessemos usar sem ser em base64, deveriamos usar stringData
  # Devemos por em base64
  user: YWRtaW4=
  pass: TXktcGFzcy0xMjM=
sringData: # Podemos combinar data e stringData
  my-database-name: mysql
# immutable: true # Imutável, caso queira tirar, deve-se reecriar o secret

# Para criar o secret use o comando:
# echo -n 'admin' | base64 -> trás a string em base64
# Para decodificar use o comando:
# echo -n 'YWRtaW4=' | base64 -d ou --decode -> decodifica a string em base64