# Existem outras formas de consumir os secrets, como por exemplo usando variáveis de ambiente, mas por boas práticas recomenda-se usar os secrets via volume, pois assim não expomos os valores sensíveis como variáveis de ambiente, e sim como arquivos dentro do container, onde cada arquivo tem o nome da chave do secret e o conteúdo do arquivo é o valor do secret. Dessa forma, evitamos que os valores sensíveis sejam expostos acidentalmente em logs ou em outros lugares onde as variáveis de ambiente possam ser acessadas. Além disso, usando volumes, podemos montar os secrets em locais específicos dentro do container, o que pode ser útil para organizar melhor a estrutura dos arquivos e facilitar o acesso aos dados sensíveis.
# Caso quira saber mais, acesse a explicação no drive.
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  type: Opaque # Type padrão é Opaque
data: # Se caso quisessemos usar sem ser em base64, deveriamos usar stringData
  # Devemos por em base64
  user: YWRtaW4=
  pass: TXktcGFzcy0xMjM=
sringData: # Podemos combinar data e stringData
  my-database-name: mysql
---
# Pod consumindo o secret via volume
kind: Pod
apiVersion: v1
metadata:
  name: pod-secret-vol-env
spec:
  containers:
  - name: secret-vol-env
    image: nginx
    envFrom:
    - SecretRef:
        name: my-secret
    volumeMounts:
    - name: my-vol
      mountPath: "/etc/secret-vol-env"
      readOnly: true
  # Definindo o volume para que possamos usar acima
  volumes:
  - name: my-vol
    secret:
      secretName: my-secret
# Podemos acessar os valores tanto pelas variáveis de ambiente(rode o comando 'env' dentro do pod) quanto pelos arquivos no volume, ambos com o mesmo nome definido no secret