# O arquivo de configuração do DaemonSet é muito parecido com o do ReplicaSet, a diferença é que no DaemonSet não precisamos especificar o número de réplicas, pois ele irá criar uma cópia do pod em cada nó(worker node) do cluster.
apiVersion: apps/v1
# kind: ReplicaSet
kind: DaemonSet
metadata:
  name: frontend-rs
  labels:
    app: frontend
spec:
  template: 
    metadata:
      name: my-pod-webserver
      labels:
        apps: my-app
        tier: frontend
    spec:
      containers:
      - name: my-container-nginx
        image: nginx
      # SELECIONANDO NODES PARA O DAEMONSET
      # Definindo o nodeSelector para que o DaemonSet seja criado apenas nos nós que possuem a label disktype: ssd
      #nodeSelector:
      #  disktype: ssd
       # Adicionando a label disktype: 
       # kubectl get nodes
       # kubectl labels nodes nome-node disktype=ssd 
       # kubectl get nodes --show-labels | grep disktype: mostra os nodes com a label disktype
      # Podemos selecionar o node usando o nome, dessa forma usamos o nodeName ao invés do nodeSelector, mas não conseguimos passar os nomes de vários nodes.
      #nodeName: minikube
      
  selector:
    matchLabels:
      apps: my-app
  # No daemonset não precisa da linha abaixo
  # replicas: 4